# Site
name: "Mas Cemplon"
title: "Mas Cemplon"
description: "Berbagi Informasi Onlien Yang Mendidik"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ""
google_analytics: 'G-S8WBW5V67Q'
disqus: 'postkomik-github-1'

include: ["_pages"]
permalink: /:title/
email: Ahmadalwy@gmail.com

# Authors
authors:
  
    
  mas cemplon:
    name: Mas Cemplon
    display_name: Mas Cemplon
    avatar: 'assets/images/avatar.png'
    email: Ahmadalwy@gmail.com
    web: https://postkomik.github.io
    twitter: https://twitter.com/
    description: "Author of postkomik, a Manga Mahua styled template available for Blogger, HTML, . You are currently previewing Website."
    
  

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-6982236787200985"
adsense-data-ad-slot: "3984526592"
adsense-data-ad-format: "auto"
# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"




# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

#exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
